### ISSUE TITLE
badgerauth: subcommands for creating certificates

### ISSUE THREAD

**Issue by egonelbre** [storj/edge#185]
It's nice to be able to easily create appropriate certificates for nodes.

Currently it's possible to use openssl command line tools to achieve the same goals.

Related to https://github.com/storj/gateway-mt/issues/179.

**Comment by halkyon** [comment]
I wonder if we could use something like https://github.com/cloudflare/cfssl to handle this more in Go instead of command line.

**Comment by egonelbre** [comment]
I'm not quite sure how it would help. It seems like it would complicate things instead. Once we generate the keys we don't need to update them for a few years.

**Comment by halkyon** [comment]
I was thinking more of the case of "i need to quickly spin up a test cluster locally" or something with new certs, but I certainly wouldn't want to overcomplicate things :)

**Comment by egonelbre** [comment]
Ah, the code to create a test CA and node keys is relatively easy. For example see https://github.com/storj/storj/blob/main/testsuite/ui/uitest/edge.go#L162.

For production, the main thing is to ensure you get the parameters of the certificates correct... but, since we are using it for mutual auth, it's less of a worry... because we control both the client and servers.

**Comment by amwolff** [comment]
I believe it should be similar to https://www.cockroachlabs.com/docs/v21.2/cockroach-cert.

It will be sufficient if we are able to create a test cluster quickly, without messing up with certificates.
