### ISSUE TITLE
badgerauth: test process start, stop and recovery

### ISSUE THREAD

**Issue by egonelbre** [storj/edge#186]
Tests with starting and stopping randomly node processes to ensure that they can recover.

Split off from https://github.com/storj/gateway-mt/issues/181.

**Comment by amwolff** [comment]
I believe this should be more like an integration test; there should be a controller (a program that has the ability to start/stop processes) that does what described. At the time we start/stop processes, we should be inserting records and check whether all nodes have these records upon test's end (whether the cluster has converged). `testcontext` has a neat instrumentation for compiling binaries/starting processes, but I'm not sure if it's possible to stop processes using it.

Maybe we can use some of the existing software for fuzzing the cluster, like https://netflix.github.io/chaosmonkey/ or https://github.com/Shopify/toxiproxy.

**Comment by egonelbre** [comment]
Adding process stopping is not too complicated -- mostly.
