### ISSUE TITLE
Make badgerauth's replication more efficient

### ISSUE THREAD

**Issue by amwolff** [storj/edge#210]
Our replication algorithm is suboptimal.

```mermaid
graph TD;
A-->B;
B-->A;
```

If node A fails to replicate records from node B before they expire, A will be fetching the latest records from B that A already has until A's clock value of B matches what B has of itself.

For a more prolonged explanation, see #208.

To fix this, we shouldn't be assuming clocks but probably send them along with records.

**Comment by ferristocrat** [comment]
@amwolff - what's the risk of never optimizing badgerauth's replication?

**Comment by amwolff** [comment]
@ferristocrat The main risk I see is confusion because it's non-obvious of what's happening if what's described in #208 happens. This is not an attack vector because it's as easy to abuse Auth Service by just sending non-expiring records. Maybe even easier because you don't need to fill out the expiration. However, to avoid that confusion risk, we can also deny putting records that expire in, e.g., less than 5 minutes (or a multiple of replication interval) to the database.

**Comment by amwolff** [comment]
An idea of how to make it better:

- Node A has 1-10 records; records 5-8 expired
- Node B is at Node A's 4th record

1. Node B replicates from Node A, supplying `A=4`
2. Node A sees it had to traverse the database from 4+1=5 up to 9 to return something
3. If Node A had to traverse, Node B would have to too. Node A supplies `start_from=8`
4. Node B first increases its `A` clock to 8 and only then starts applying new records

There are probably some caveats I haven't yet thought about.

**Comment by ferristocrat** [comment]
Do we need another issue for adding more logging that you reference at the end of this comment @amwolff  https://github.com/storj/gateway-mt/issues/208#issuecomment-1152283080 ?

**Comment by amwolff** [comment]
@ferristocrat no, that is already done
