### ISSUE TITLE
[Linksharing TLS] Change traefik's config

### ISSUE THREAD

**Issue by shaupt131** [storj/edge#264]
### Goal

- Stop traefik do the termination of TLS and hand it over to linksharing.

### Acceptance Criteria

- Custom Domains @ TLS is fully deployed to prod.

### Links

 -

**Comment by NiaStorj** [comment]
@adaRn what is the status of this ticket? Will it be completed before your PTO?

**Comment by NiaStorj** [comment]
@adaRn ticket #238 is closed. Are you able to start on this now?

**Comment by nergdron** [comment]
note: here's the code branch I have prepped for this:

https://github.com/storj/infra/tree/tn/linksharing-strip-tls

**Comment by nergdron** [comment]
linksharing config changes from artur:

https://review.dev.storj.io/c/storj/gateway-mt/+/8602

```
+# email address to use when creating an ACME account
+cert-magic.email: ""
+
+# bucket to use for certificate storage
+cert-magic.bucket: ""
+
+# use CertMagic to handle TLS certificates
+cert-magic.enabled: false
+
+# path to the service account key file
+cert-magic.key-file: ""
+
+# use staging CA endpoints
+cert-magic.staging: false
+

-# use lets-encrypt to handle TLS certificates
-lets-encrypt: false
```

**Comment by nergdron** [comment]
blocked on https://github.com/storj/infra/issues/3461
