### ISSUE TITLE
Update MIME Type Documentation

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#266]
### Goal

- Document mime type defaults and options as described here: https://github.com/storj/gateway-mt/issues/60#issuecomment-1267796850

### Acceptance Criteria

- Update documentation for mime-types

### Links

 - N/A

**Comment by halkyon** [comment]
This is already documented here: https://github.com/storj/gateway-mt/blob/main/docs/linksharing.md#custom-response-metadata but it might be good to surface it as a page somewhere in https://docs.storj.io/

**Comment by NiaStorj** [comment]
@ferristocrat go through all of the edge docs.

**Comment by halkyon** [comment]
https://github.com/storj/docs/pull/465
