### ISSUE TITLE
Add Pagination to Linksharing Lists

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#309]
### What is the problem/pain point?

- We currently don't have any pagination for linkshare lists
- For buckets/paths that are sufficiently large this will likely lead to weird behavior in the browser (or just using all available resources to load the entire list)
- See https://github.com/storj/gateway-mt/blob/90f6a17c1445ced1cf9008ec024e1503975646aa/pkg/linksharing/sharing/list.go#L82

### Who is impacted?

- Linksharing customers

### What is the impact?

- Things breaking unexpectedly

### Why now?

- Not the most important, but we should at least come up with our desired solution

### Acceptance Criteria

- List requests are paginated

### Success Metrics

- TBD

**Comment by amwolff** [comment]
It might be cool to have infinite scroll, but of course, it's a design decision.

**Comment by amwolff** [comment]
I think, as a start, we could limit the page to have a maximum of 1000 results with a note that to see more results use the gateway or uplink CLI or libuplink.
