### ISSUE TITLE
S3 Support for Object Versioning on Storj

### ISSUE THREAD

**Issue by NiaStorj** [storj/edge#363]
### Overview
The objective is to integrate support for S3 object versioning. This is meant to be parent issue to capture high  level requirements.

### Acceptance Criteria
- PutBucketVersioning
  - Object versioning can be enabled for a bucket
  - Object versioning can be disabled for a bucket
    - When object versioning is disabled:
      - All existing versions are still maintained unless manually deleted
      - Any new versions will follow the behavior described below for PutObject
- GetBucketVersioning
  - The state of bucket version can be requested. The possible states are:
    - Enabled
    - Disabled
    - Suspended
- ListObjectVersions
  - Passes all relevant tests for `ListObjectVersions`
- GetObject
  - VersionId should be added as a request parameter to retrieve the specific object version
  -  Response should include:
     - `x-amz-version-id`: Version of the object.
- HeadObject
  - VersionId should be added as a request parameter to retrieve the specific object version
  -  Response includes:
     - `x-amz-version-id`: Version of the object.
- PutObject
  - For buckets with versioning enabled:
    - When an object that already exists (same name) is uploaded to a bucket:
      - A new copy of the object is stored with a new unique version ID
  - For buckets with versioning disabled:
    - When an object that already exists (same name) is uploaded to a bucket:
      - The latest version of the object is overwritten by the new object
      - The new object has a version ID of null
      - Versions older than the most recent version will not be impacted (this will only happen if versioning was previously enabled – in this instance they need to be manually deleted if desired)
  - Response includes:
    - `x-amz-version-id`: Version of the object.
- CompleteMultipartUpload
  - Same behavior as PutObject
  - Response includes:
    - `x-amz-version-id`: Version of the object.
- DeleteObject (need to validate against what has been implemented on Satellite)
  - A DeleteObject request should accept an optional VersionId, which references a specific version of the object
  - Response includes:
    - `x-amz-version-id`: The version ID of the delete marker created as a result of the DELETE operation
    - `x-amz-delete-marker`: Boolean that indicates whether the specified object version that was permanently deleted was (true) or was not (false) a delete marker before deletion. In a simple DELETE, this header indicates whether (true) or not (false) the current version of the object is a delete marker.
- DeleteObjects
  - Each Delete "Object" in a DeleteObjects request should accept an optional VersionId (in addition to the object Key), which references a specific version of the object
  - Response includes:
    - `DeleteMarker`: Boolean that indicates whether the specified object version that was permanently deleted was (true) or was not (false) a delete marker before deletion. In a simple DELETE, this header indicates whether (true) or not (false) the current version of the object is a delete marker.
    - `DeleteMarkerVersionId`: The version ID of the delete marker created as a result of the DELETE operation.
    - `VersionId`: The version ID of the deleted object.
- PutObjectTagging
  - VersionId should be added as a request parameter to specify the specific version of the object that the tag-set will be added to
  - Response includes:
    - `x-amz-version-id`: The versionId of the object the tag-set was added to.
- GetObjectTagging
  - VersionId should be added as a request parameter to retrieve the tagging information for a specific object version
  -   Response includes:
      - `x-amz-version-id`: The versionId of the object for which you got the tagging information.
- DeleteObjectTagging
  - VersionId should be added as a request parameter to specify the specific versioned oibject to remove the tag-set from
  -  Response includes:
     - `x-amz-version-id`: The versionId of the object the tag-set was removed from.

```[tasklist]
### Tasks
- [ ] https://github.com/storj/gateway-mt/issues/368
```

**Comment by shaupt131** [comment]
PutObjectTagging and DeleteObjectTagging are lower-priority items that we probably won't complete under this ticket.  We will break these out into a separate ticket that we can file as an enhancement for later.

**Comment by shaupt131** [comment]
Upsized ticket estimation to an 8.

**Comment by shaupt131** [comment]
@mniewrzal to confirm if we have tickets to cover anything not covered within this ticket, then close.

**Comment by mniewrzal** [comment]
I think we all tickets we need atm. Closing.
