### ISSUE TITLE
Understand if all necessary placeholders exist in Gateway-{ST,MT} for versioning to work

### ISSUE THREAD

**Issue by amwolff** [storj/edge#368]
### Objective
The goal of this issue is to ensure that the gateway has all the necessary placeholders for handling the following S3 actions, to expedite the connection to the underlying Satellite actions when they become available for use.

### Actions to verify 
- PutBucketVersioning
  - Object versioning can be enabled for a bucket
  - Object versioning can be disabled for a bucket
    - When object versioning is disabled:
      - All existing versions are still maintained unless manually deleted
      - Any new versions will follow the behavior described below for PutObject
- GetBucketVersioning
  - The state of bucket version can be requested. The possible states are:
    - Enabled
    - Disabled
    - Suspended
- ListObjectVersions
  - Passes all relevant tests for `ListObjectVersions`
- GetObject
  - VersionId should be added as a request parameter to retrieve the specific object version
  -  Response should include:
     - `x-amz-version-id`: Version of the object.
- HeadObject
  - VersionId should be added as a request parameter to retrieve the specific object version
  -  Response includes:
     - `x-amz-version-id`: Version of the object.
- PutObject
  - For buckets with versioning enabled:
    - When an object that already exists (same name) is uploaded to a bucket:
      - A new copy of the object is stored with a new unique version ID
  - For buckets with versioning disabled:
    - When an object that already exists (same name) is uploaded to a bucket:
      - The latest version of the object is overwritten by the new object
      - The new object has a version ID of null
      - Versions older than the most recent version will not be impacted (this will only happen if versioning was previously enabled – in this instance they need to be manually deleted if desired)
  - Response includes:
    - `x-amz-version-id`: Version of the object.
- CompleteMultipartUpload
  - Same behavior as PutObject
  - Response includes:
    - `x-amz-version-id`: Version of the object.
- DeleteObject (need to validate against what has been implemented on Satellite)
  - A DeleteObject request should accept an optional VersionId, which references a specific version of the object
  - Response includes:
    - `x-amz-version-id`: The version ID of the delete marker created as a result of the DELETE operation
    - `x-amz-delete-marker`: Boolean that indicates whether the specified object version that was permanently deleted was (true) or was not (false) a delete marker before deletion. In a simple DELETE, this header indicates whether (true) or not (false) the current version of the object is a delete marker.
- DeleteObjects
  - Each Delete "Object" in a DeleteObjects request should accept an optional VersionId (in addition to the object Key), which references a specific version of the object
  - Response includes:
    - `DeleteMarker`: Boolean that indicates whether the specified object version that was permanently deleted was (true) or was not (false) a delete marker before deletion. In a simple DELETE, this header indicates whether (true) or not (false) the current version of the object is a delete marker.
    - `DeleteMarkerVersionId`: The version ID of the delete marker created as a result of the DELETE operation.
    - `VersionId`: The version ID of the deleted object.
- PutObjectTagging
  - VersionId should be added as a request parameter to specify the specific version of the object that the tag-set will be added to
  - Response includes:
    - `x-amz-version-id`: The versionId of the object the tag-set was added to.
- GetObjectTagging
  - VersionId should be added as a request parameter to retrieve the tagging information for a specific object version
  -   Response includes:
      - `x-amz-version-id`: The versionId of the object for which you got the tagging information.
- DeleteObjectTagging
  - VersionId should be added as a request parameter to specify the specific versioned oibject to remove the tag-set from
  -  Response includes:
     - `x-amz-version-id`: The versionId of the object the tag-set was removed from.

```[tasklist]
### Tasks
- [ ] PutBucketVersioning
- [ ] GetBucketVersioning
- [ ] ListObjectVersions
- [ ] GetObject
- [ ] HeadObject
- [ ] PutObject
- [ ] CompleteMultipartUpload
- [ ] DeleteObject
- [ ] DeleteObjects
- [ ] PutObjectTagging
- [ ] GetObjectTagging
- [ ] DeleteObjectTagging
```

**Comment by amwolff** [comment]
Jeremy had some feedback that what this task wants to accomplish is confusing, and I agree; the issue states that what should be done is verification if all placeholders exist while specifying what the expected behavior is. This list is a copy-paste from another issue, so that's probably why it's like that. Regardless, I think what we should do as part of this is verification if all placeholders exist along with data structures necessary for these actions to exhibit the expected behavior. So for example: `DeleteObjectTagging`: if the implementation of this action is already supported within our codebase, we should only verify if the code supports responding with something so that `x-amz-version-id` header will be returned (if there's nothing like that, maybe our underlying dependencies (minio) won't even respond with that header?). We should also verify if `DeleteObjectTagging` allows users to specify the version ID to be removed. If data structures of code for handling this action already include such a construct, we can be confident that clients will be able to communicate that, allowing this action to work the way we want here. @jewharton what do you think?

**Comment by jewharton** [comment]
@amwolff That sounds good to me. Thanks for clarifying.

**Comment by jewharton** [comment]
Evaluations were made based on the following versions:  

* Gateway ST: `storj/gateway-st@3a5764f`
* Gateway MT: `storj/edge@0c1c0d3`
* MinIO: `storj/minio@f1d4dd3`

---

* PutBucketVersioning
	* :warning: Object versioning can be enabled/disabled for a bucket
		* Gateway MT: [Yes](https://github.com/storj/edge/blob/af3395eddfa445a895ff84c3dc94a8b5979589df/pkg/minio/api-router.go#L224)
			* As of the time of writing, Gateway MT uses a version of Minio that doesn’t require the `SetBucketVersioning` [method](https://github.com/storj/minio/blob/730e38e5b7abe92a7438f6c3ee0312e5daf55a34/cmd/object-api-interface.go#L113) of Minio’s object layer interface to be implemented. Once the Minio dependency version is bumped to `730e38e` or beyond, Gateway MT must implement this.
		* Gateway ST: No
* GetBucketVersioning
	* :warning: A bucket’s versioning status can be requested.
		* Gateway MT: [Yes](https://github.com/storj/edge/blob/af3395eddfa445a895ff84c3dc94a8b5979589df/pkg/minio/api-router.go#L137)
			* As of the time of writing, Gateway MT uses a version of Minio that doesn’t require the `GetBucketVersioning` [method](https://github.com/storj/minio/blob/730e38e5b7abe92a7438f6c3ee0312e5daf55a34/cmd/object-api-interface.go#L113) of Minio’s object layer interface to be implemented. Once the Minio dependency version is bumped to `730e38e` or beyond, Gateway MT must implement this.
		* Gateway ST: No
	* :warning: The possible states are:
		* Enabled ([Supported](https://github.com/storj/minio/blob/f1d4dd3/pkg/bucket/versioning/versioning.go#L30))
		* Disabled ([Unsupported](https://github.com/storj/minio/blob/f1d4dd3/pkg/bucket/versioning/versioning.go#L31); this state is only used by MFA delete, an unsupported feature)
		* Suspended ([Supported](https://github.com/storj/minio/blob/f1d4dd3/pkg/bucket/versioning/versioning.go#L32))
* ListObjectVersions
	* :x: This action produces a "not implemented" error because the gateway’s [single tenancy layer](https://github.com/storj/gateway-st/blob/6a3551bf46260fc8eb8ec99f08bdde20617bbfb5/miniogw/single_tenant.go) does not provide an implementation for it.
	* :warning: Passes all relevant tests for `ListObjectVersions`.
		* The [test](https://github.com/storj/gateway-st/blob/74654d9d40281889482389784a96e1ebdea672a3/testsuite/miniogw/gateway_test.go#L3460) for this method passes, but it only verifies that the method returns a "not implemented" error.
* GetObject
	* :x: `VersionId` should be added as a request parameter to retrieve the specific object version.
		* Minio [parses](https://github.com/storj/minio/blob/f1d4dd3/cmd/object-api-options.go#L96) this value and passes it ([\[1\]](https://github.com/storj/minio/blob/f1d4dd3/cmd/object-handlers.go#L333), [\[2\]](https://github.com/storj/minio/blob/f1d4dd3/cmd/object-handlers.go#L418)) to the object API, but the gateway [never uses it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L715).
	* :x: Response should include `x-amz-version-id`, the version of the object.
		* Minio is capable of returning this value ([\[1\]](https://github.com/storj/minio/blob/f1d4dd3/cmd/object-handlers.go#L487), [\[2\]](https://github.com/storj/minio/blob/f1d4dd3/cmd/api-headers.go#L180)), but the gateway [never assigns it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1235).
* HeadObject
	* :x: `VersionId` should be added as a request parameter to retrieve the specific object version.
		* Minio [parses](https://github.com/storj/minio/blob/f1d4dd3/cmd/object-api-options.go#L96) this value and passes it ([\[1\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L576), [\[2\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L613)) to the object API, but the gateway [never uses it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L781).
	* :x: Response includes `x-amz-version-id`, the version of the object.
		* Minio is capable of returning this value ([\[1\]](https://github.com/storj/minio/blob/f1d4dd3/cmd/object-handlers.go#L487), [\[2\]](https://github.com/storj/minio/blob/f1d4dd3/cmd/api-headers.go#L180)), but the gateway [never assigns it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1235).
* PutObject
	* :x: There is no special handling for versioned objects in the gateway’s `PutObject` [implementation](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L803). As a result, none of the following are true:
		* For buckets with versioning enabled:
			* When an object that already exists (same name) is uploaded to a bucket:
				* A new copy of the object is stored with a new unique version ID
		* For buckets with versioning disabled:
			* When an object that already exists (same name) is uploaded to a bucket:
				* The latest version of the object is overwritten by the new object
				* The new object has a version ID of null
				* Versions older than the most recent version will not be impacted (this will only happen if versioning was previously enabled – in this instance they need to be manually deleted if desired)
	* :x: Response includes `x-amz-version-id`, the version of the object.
		* Minio is capable of returning this value ([\[1\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L1604), [\[2\]](https://github.com/storj/minio/blob/7ad3f562f009c04cb4147131e7be69236ae6ac15/cmd/object-handlers-common.go#L255)), but the gateway [never assigns it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1235).
* CompleteMultipartUpload
	* :x: Same expected behavior as `PutObject`
		* There is no special handling for versioned objects in the gateway’s `CompleteMultipartUpload` [implementation](https://github.com/storj/gateway-st/blob/dc69596a6a6cca84f2e2684a7e600f43dd31c9ac/miniogw/multipart.go#L321).
	* :x: Response includes `x-amz-version-id`, the version of the object.
		* Minio is capable of returning this value ([\[1\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L2969), [\[2\]](https://github.com/storj/minio/blob/7ad3f562f009c04cb4147131e7be69236ae6ac15/cmd/object-handlers-common.go#L255)), but the gateway [never assigns it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1235).
* DeleteObject (need to validate against what has been implemented on Satellite)
	* :x: `VersionId` should be added as a request parameter to delete a specific object version.
		* Minio uses this value in its [API handler](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L2992) for this action and passes it ([\[1\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3021), [\[2\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3092)) to the object API, but the gateway [never uses it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L969).
	* :x: Response includes:
		* `x-amz-version-id`: The version ID of the delete marker created as a result of the DELETE operation
		* `x-amz-delete-marker`: Boolean that indicates whether the specified object version that was permanently deleted was (true) or was not (false) a delete marker before deletion. In a simple DELETE, this header indicates whether (true) or not (false) the current version of the object is a delete marker.
		* Minio is capable of returning these values ([\[1\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3107), [\[2\]](https://github.com/storj/minio/blob/7ad3f562f009c04cb4147131e7be69236ae6ac15/cmd/object-handlers-common.go#L254)), but the gateway [never assigns them](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1235).
* DeleteObjects
	* :question: Unknown. I don’t see any handlers for this action, so I don’t know whether we support it. I’ll update this once I get more info.
* PutObjectTagging
	* :x: `VersionId` should be added as a request parameter to specify the specific version of the object that the tag-set will be added to.
		* Minio [parses](https://github.com/storj/minio/blob/9ac531da7cb4459f3fe3a91e15c5a7cbcc1e195f/cmd/object-api-options.go#L96) this value and passes it ([\[1\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3593), [\[2\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3608)) to the object API, but the gateway [never uses it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1028).
	* :x: Response includes `x-amz-version-id`, the version ID of the object the tag-set was added to.
		* Minio is [capable](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3619) of returning this value, but the gateway [never assigns it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1235).
* GetObjectTagging
	* :x: `VersionId` should be added as a request parameter to retrieve the tagging information for a specific object version.
		* Minio [parses](https://github.com/storj/minio/blob/9ac531da7cb4459f3fe3a91e15c5a7cbcc1e195f/cmd/object-api-options.go#L96) this value and [passes](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3538-L3545) it to the object API, but the gateway [never uses it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1066).
	* :x: Response includes `x-amz-version-id`, the version ID of the object for which you got the tagging information.
		* Minio is [capable](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3552) of returning this value, but the gateway [never assigns it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1235).
* DeleteObjectTagging
	* :x: `VersionId` should be added as a request parameter to specify the specific versioned object to remove the tag-set from.
		* Minio [parses](https://github.com/storj/minio/blob/9ac531da7cb4459f3fe3a91e15c5a7cbcc1e195f/cmd/object-api-options.go#L96) this value and passes it ([\[1\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3665), [\[2\]](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3682)) to the object API, but the gateway [never uses it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1093).
	* :x: Response includes `x-amz-version-id`, the version ID of the object the tag-set was removed from.
		* Minio is [capable](https://github.com/storj/minio/blob/eb9c3875df54210b47a60fb92a069449131fcfc9/cmd/object-handlers.go#L3693) of returning this value, but the gateway [never assigns it](https://github.com/storj/gateway-st/blob/381303f6b5550c72790954c1ff2dbf13d8c54728/miniogw/gateway.go#L1235).
