### ISSUE TITLE
Passing Snowflake Tests: Weird behavior from GetBucketLocation

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#372]
## Expected Behavior

Expect snowflake tests to pass, but they don't.

```
set -euo pipefail

# create buckets snowflake and sf-non-existing-bucket and deny
# create file at deny/src/main/resources/test1.txt
# create S3 credentials with permission to snowflake and sf-non-existing-bucket
# remove sf-non-existing-bucket
# create 2048 files at snowflake/lots/

export S3COMPAT_ACCESS_KEY=  # Access key to used to acess to the above bucket.
export S3COMPAT_SECRET_KEY=  # Secret key to used to access to the above bucket.
export BUCKET_NAME_1=snowflake      # The bucket name for testing, locate at REGION_1, expect versioning enabled.
export REGION_1=global              # Region for the above bucket, like us-east-1.
export REGION_2=us-west-2           # Region that is different than REGION_1, like us-west-2.
export END_POINT=https://gateway.storjshare.io/ # End point that can route operations to the provided bucket.
export NOT_ACCESSIBLE_BUCKET=deny   # A bucket that is not accessible by the provided keys, at REGION_1.
export PREFIX_FOR_PAGE_LISTING=lots # The prefix for testing listing large num of objects, at BUCKET_NAME_1, it needs to have over 1000 objects. 
export PAGE_LISTING_TOTAL_SIZE=2049 # The total size of objects on the above prefix: PREFIX_FOR_PAGE_LISTING.


export AWS_ACCESS_KEY_ID=$S3COMPAT_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$S3COMPAT_SECRET_KEY 

# aws s3 --endpoint=$END_POINT mb s3://$BUCKET_NAME_1 || true

# echo creating
# for (( I=0 ; I < PAGE_LISTING_TOTAL_SIZE-1 ; I++ )) ; do
#         head -c 65536 /dev/zero | aws s3  --endpoint=$END_POINT cp - s3://$BUCKET_NAME_1/$PREFIX_FOR_PAGE_LISTING/$I
# done

mvn test -Dtest=S3CompatApiTest
```

## Current Behavior

The only error @wthorp  can't avoid is with GetBucketLocation.

Errors with `export REGION_1=us-east-1`:
```
[ERROR]   S3CompatApiTest.getBucketLocation:87 expected: <us-east-1> but was: <global>
```
Errors with `export REGION_1=global`:
```
[ERROR]  S3CompatApiTest.getBucketLocation:91 expected: <global> but was: <null>
```

Seems like weird behavior.

## Acceptance Criteria
Review responses, and propose solution/workaround if feasible.

**Comment by ferristocrat** [comment]
I assume the answer is "we don't technically support regions like aws so those tests are never going to pass" but the behavior seems strange nonetheless so I think we should investigate.

**Comment by amwolff** [comment]
The second failure is weird considering we don't really take the region because of "we don't technically support regions like aws so those tests are never going to pass", so the second test case should also end with `global`.

**Comment by amwolff** [comment]
It would be fantastic to add Snowflake's tests to our test suites that we run regularly.

**Comment by ferristocrat** [comment]
@amwolff - should we change the acceptance criteria to "add snowflakes tests to our test suites"?

Ultimately, we want to answer the question of "how can we pass the tests," so hoping that they don't have AWS regions hardcoded (such as `us-east-1`) because we'd need to implement some bad behavior to "force" that to pass.

**Comment by ferristocrat** [comment]
Summarizing some investigation with Artur:

1. Errors with export REGION_1=us-east-1:
   - ```[ERROR]   S3CompatApiTest.getBucketLocation:87 expected: <us-east-1> but was: <global>```
   - This error is happening because GetBucketLocation returns `global` rather than `us-east-1` with Storj -- this is expected as we do not have anything that would return `us-east-1`

2. Errors with export REGION_1=global:
   - ```[ERROR]  S3CompatApiTest.getBucketLocation:91 expected: <global> but was: <null>```
   - Given the error from using `us-east-1`, you would expect this to return `global` but it is null. The reason for this is that the line 87 of the test passes (calling GetBucketLocation) but then line 91 is run, which fails. The failure is in using HeadObject which the test expects to return `x-amz-bucket-region` which we do not

We seem to have two options:
1. Do nothing/talk with Snowflake > The test suite readme says to ignore the error coming from line 91 above (see more explanation in the Readme below):
   - Readme reference: https://github.com/snowflakedb/snowflake-s3compat-api-test-suite/blob/e9ec456869c693acda96ca91b6547394a27459d0/Readme.md?plain=1#L133
   - Relevant line in the test: https://github.com/snowflakedb/snowflake-s3compat-api-test-suite/blob/e9ec456869c693acda96ca91b6547394a27459d0/s3compatapi/src/test/java/com/snowflake/s3compatapitestsuite/compatapi/S3CompatApiTest.java#L90C1-L90C1
2. Update HeadObject to return `x-amz-bucket-region` header
   - Note that the [AWS S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html) says:
     > We recommend that you use [HeadBucket](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) to return the Region that a bucket resides in. For backward compatibility, Amazon S3 continues to support GetBucketLocation.

**Comment by ferristocrat** [comment]
@wthorp - Can you take a look at the two options above and provide your thoughts on whether or not we may just be okay with the failure? A slight alternative to option 1 above, is to submit a PR to the test suite such that line 87 and line 91 in the test become an OR condition (only one needs to pass as the README implies)

**Comment by wthorp** [comment]
I like option #2 best.  This seems relatively easy to do and removes potential friction.

**Comment by amwolff** [comment]
This can be closed if https://github.com/snowflakedb/snowflake-s3compat-api-test-suite/pull/60 gets accepted.

**Comment by amwolff** [comment]
For posterity, this is how I ran it:

```sh
uplink mb --access qa sj://sf1
uplink share --register --readonly=false --access qa --auth-service https://ngb1-hz.auth.staging.tardigradeshare.io sj://sf1/ sj://sf-non-existing-bucket/
s3-create-objects https://ngb1-hz.stargate.staging.tardigradeshare.io AKID SAK sf1 p 1234

docker run \
  -it \
  --rm \
  --name snowflake-s3compat-api-test-suite \
  -e BUCKET_NAME_1=sf1 \
  -e REGION_1=global \
  -e REGION_2=global2 \
  -e S3COMPAT_ACCESS_KEY=AKID \
  -e S3COMPAT_SECRET_KEY=SAK \
  -e END_POINT=https://ngb1-hz.stargate.staging.tardigradeshare.io \
  -e NOT_ACCESSIBLE_BUCKET=sf2 \
  -e PREFIX_FOR_PAGE_LISTING=p \
  -e PAGE_LISTING_TOTAL_SIZE=1234 \
  -v "$(pwd)":/usr/src/snowflake-s3compat-api-test-suite \
  -w /usr/src/snowflake-s3compat-api-test-suite \
  maven:latest /bin/bash

cat << EOF > ~/.m2/settings.xml
<settings>
  <servers>
    <server>
      <id>github</id>
      <username>username</username>
      <password>password</password>
    </server>
  </servers>
</settings>
EOF

mvn clean install -DskipTests && mvn test -Dtest=S3CompatApiTest
```
