### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#376]
## Motivation/Why?

We want to document the release process so we can make it consistent and repeatable.

## What needs to be done?

Work with @andriikotko to understand how the release process has been executed in the past.

## Acceptance Criteria

- Create an issue template with a tasklist-based checklist that outlines what needs to be done to complete the release process, including what tests need to be run and what documentation needs updating
- (optional) Identify opportunities for automation

**Comment by neo-cypher** [comment]
Tasks:
- [ ] Pull Request template
- [ ] Change log generation
- [ ] Document deployment process

**Comment by amwolff** [comment]
Any news on the PR with the template @neo-cypher? Do you need any help?

**Comment by neo-cypher** [comment]
Almost complete. Should be sending out a request for review here shortly.
