### ISSUE TITLE
Review Linksharing Log Technical Design

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#379]
### Goal

- Review Kaloyan's design for supporting linksharing logs feature and approve or suggest changes

### Acceptance Criteria

- Review https://github.com/storj/design-docs/pull/11
- Propose ROM:
  - 0.5 = XS   (1 sprint or less)
  - 1 = S   (1-2 sprints)
  - 2  = M   (3-4 sprints)
  - 3 = L   (5-6 sprints)
  - 5 = XL   (7-8 sprints)
  - 8 = XXL   (9+ sprints)

### Links

 - [Technical design doc](https://github.com/storj/design-docs/pull/11)

**Comment by amwolff** [comment]
from sprint planning: @kaloyan-raev will add some links here to resources for better understanding how Grafana Loki works.

**Comment by amwolff** [comment]
AFAIR @pwilloughby proposed 2 = M (3-4 sprints) as a ROM for the MVP.
