### ISSUE TITLE
Object Lock: Document edge cases/impact on other S3 methods

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#396]
### What is the problem/pain point?

- We want to document the impact of implementing S3 Object lock on other S3 methods that are not directly related to Object Lock, such as PutObject.

### Acceptance Criteria

- Document how the following S3 methods impact what's needed for other methods:
   - GetObjectLockConfiguration
   - PutObjectLockConfiguration
   - GetObjectRetention
   - PutObjectRetention
   - GetObjectLegalHold
   - PutObjectLegalHold
  
For example, PutObject has "x-amz-object-lock-retain-until-date" as a request parameter that we'll need to consider.

### Next steps
Current thought is that creating a "shim implementation" will help us identify the above, so consider combining these two issues: https://github.com/storj/edge/issues/397

**Comment by amwolff** [comment]
- new permissions
- needs modification: `PutObject`
- needs modification: `CopyObject`
- needs modification: `GetObject`
- needs modification: `CreateMultipartUpload`
- needs modification: `CompleteMultipartUpload`
- needs modification: `DeleteBucket` (forceful deletion)
- needs modification: `HeadObject`
- needs modification: `UploadPart`
- new endpoint: `PutObjectLegalHold`
- new endpoint: `PutObjectLockConfiguration`
- new endpoint: `PutObjectRetention`
- new endpoint: `GetObjectLegalHold`
- new endpoint: `GetObjectLockConfiguration`
- new endpoint: `GetObjectRetention`
