### ISSUE TITLE
Create a gateway-only partial implementation of Object Lock

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#397]
## Goal

Completing this will make it possible to enable some object lock tests and determine how well we understand Object Lock.

## What needs to be done? • Acceptance Criteria

Gateway-only/shim implementation means all tricks allowed. The state related to object lock can be stored in the object version's user metadata and can be modifiable outside the gateway (or even within the gateway!). The purpose of this is to make tests pass and figure out if there's anything that we missed during requirements gathering.

We only need to implement a small subset of Object Lock (for example, Legal Hold is out of scope at this moment). What needs to be implemented is defined in Object Lock milestone MVP section. To recap, it's:

- https://github.com/storj/edge/issues/401
- https://github.com/storj/edge/issues/402
- https://github.com/storj/edge/issues/403
- GetObject
- HeadObject

So you only need to implement the above gateway-side only. This is very similar to what JT did for object versioning: [miniogw/versioning: introduce object versioning wrapper
](https://review.dev.storj.io/c/storj/gateway/+/10925)

## Depends on…

This issue does not depend on anything and can be worked on immediately.

## Links

- an easy-to-read and insightful introduction to Object Lock: [Using S3 Object Lock](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html)

**Comment by pwilloughby** [comment]
should this include retention periods set on the bucket?
