### ISSUE TITLE
Create a test plan for partial implementation of Object Lock

### ISSUE THREAD

**Issue by amwolff** [storj/edge#405]
## Goal

This issue is to make meaningful progress on Object Lock implementation within core and edge services. Specifically, to support immutable backups in backup software products like Veeam.

## What needs to be done? • Acceptance Criteria

We only need to implement a small subset of Object Lock (for example, Legal Hold is out of scope at this moment) first. What needs to be implemented is defined in Object Lock milestone MVP section. To recap, it's:

- https://github.com/storj/edge/issues/401
- https://github.com/storj/edge/issues/402
- https://github.com/storj/edge/issues/403
- https://github.com/storj/edge/issues/407
- https://github.com/storj/edge/issues/408

What needs to be done is a test plan to

1. test fundamental function of aforementioned partial implementation
2. test S3-specific corner cases within the boundaries of the partial implementation
2. test Storj-specific corner cases within the boundaries of the partial implementation

Use a known template for test plans, if there is one.

## Depends on…

This issue does not depend on anything and can be worked on immediately.

## Links

- an easy-to-read and insightful introduction to Object Lock: [Using S3 Object Lock](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html)

**Comment by neo-cypher** [comment]
https://docs.google.com/document/d/1nxdeLJTJeIdgi3P35z_UQ9CkTN_MDUUIvrgsPYb6EUo/edit?usp=sharing

**Comment by kaloyan-raev** [comment]
@neo-cypher A few things that should be reflected in the test plan:
- Governance mode is outside the MVP scope. Any actions related to governance mode should return an appropriate error.
- Same for legal hold.
- Once enabled, object lock cannot be disabled on a bucket.
- If a bucket is created with object lock enabled, the object versioning is also enabled for the bucket.
- Suspending or disabling object versioning is not possible for a bucket with object lock enabled.
- Force deletion is not possible for a bucket with object lock enabled.
- Setting a default retention period for a bucket is outside of the MVP scope. Any attempt to do so should return an appropriate error.
- The retention period on an object version can be extended, but it cannot be reduced.
- We should have more specific test cases related to the new `Lock` permission.
- The object lock is set on individual object versions, not on the object as a whole. if the current version of an object is locked, it should still be possible to upload newer versions on the same object and operate with them.

**Comment by neo-cypher** [comment]
@kaloyan-raev, I appreciate you taking the time to review this test plan. I had the scope incorrect so it skewed the requirements. Thanks for the corner cases, those are super helpful; as well as pointing out that when object lock is enabled that object versioning too is enabled and cannot be disabled or suspended. I'll get this feedback into the plan and update the scope to match our MVPs.

**Comment by neo-cypher** [comment]
A few things that should be reflected in the test plan:
- ~~ Governance mode is outside the MVP scope. Any actions related to governance mode should return an appropriate error. ~~
- ~~ Same for legal hold. ~~
- ~~ Once enabled, object lock cannot be disabled on a bucket. ~~
- If a bucket is created with object lock enabled, the object versioning is also enabled for the bucket.
- Suspending or disabling object versioning is not possible for a bucket with object lock enabled.
- ~~ Force deletion is not possible for a bucket with object lock enabled. ~~
- ~~ Setting a default retention period for a bucket is outside of the MVP scope. Any attempt to do so should return an appropriate error. ~~
- The retention period on an object version can be extended, but it cannot be reduced.
- We should have more specific test cases related to the new `Lock` permission.
- The object lock is set on individual object versions, not on the object as a whole. if the current version of an object is locked, it should still be possible to upload newer versions on the same object and operate with them.

**Comment by VitaliiShpital** [comment]
test plan
https://docs.google.com/document/d/1pGOhPTJGec0OogL0bM-qYVgnV8C8S7O9G08yKPXWWU8/edit#heading=h.vrh4b75a77jw
