### ISSUE TITLE
Add `GetBucketLocation` tests to release checklist

### ISSUE THREAD

**Issue by amwolff** [storj/edge#409]
We need to add some tests to ensure `GetBucketLocation` is working correctly before we make a release. This is one of the endpoints where E2E tests correctness is dependent on whether there were necessary dependency bumps made before making a release. We should design a simple test that allows us to ensure that this endpoint is working with the scheduled satellite release.

This could be something as simple as:

1. Create a bucket
2. Call GetBucketLocation
    - `aws --endpoint-url https://s3.storjapi.io s3api get-bucket-location --bucket demo-bucket`
4. Ensure that the created bucket has the necessary location constraint as per [the documentation](https://docs.storj.io/dcs/api/s3/s3-compatibility#get-bucket-location).

The acceptance criteria are to put the exact steps in the release checklist template.

**Comment by amwolff** [comment]
oh, yep, awscli is likely easier. I'll update the issue. Thanks!

**Comment by neo-cypher** [comment]
https://build.dev.storj.tools/job/edge-gerrit/7156/
