### ISSUE TITLE
Bundle static assets

### ISSUE THREAD

**Issue by amwolff** [storj/edge#425]
## Goal

Link Sharing Service static assets need to be bundled into the binary to streamline deployment and ensure their availability within the application.

## What needs to be done?

- Investigate the current storage and handling of Link Sharing Service static assets
- Explore the use of `embed.FS` to bundle static assets into the binary
- Determine the optimal method for organizing and accessing bundled static assets within the application
- Implement the necessary changes to incorporate Link Sharing Service static assets into the binary

## AC

- Successful bundling of Link Sharing Service static assets into the binary using `embed.FS`
- Verification that the bundled assets are accessible and functional within the application
- Documentation detailing the process for bundling static assets and any considerations for future updates or maintenance

**Comment by pwilloughby** [comment]
Salt can't checkout the assets from github?  I assume it's going to be pulling down the binaries from there so it seems like it should be able to handle a few more files pretty easily.

**Comment by amwolff** [comment]
yeah, I suppose it's optional. I'll lower the priority of this.

**Comment by pwilloughby** [comment]
zip up the assets along with the release binary? The bundling would be nice if it's not more effort, having software delivered as multiple files feels pretty standard to me.

**Comment by halkyon** [comment]
@jewharton This change looks great. Well done!
