### ISSUE TITLE
Make it possible to retrieve the public project ID (or a fingerprint of it) from the satellite

### ISSUE THREAD

**Issue by amwolff** [storj/edge#438]
### Goal

It would be useful for edge services to be able to retrieve and know what the public project ID tied to the access grant at hand is. It would be most useful to have it in logs.

### Acceptance Criteria

Satellite has a new endpoint or there's another endpoint that can be adjusted to respond with public project ID and libuplink has a private API added that enables using the endpoint on the client side.

### Links

An example of such endpoint: [satellite/console/userinfo/endpoint.go](https://github.com/storj/storj/blob/9870d3e1e705574f3099f9a16eadd0ed8c4045d4/satellite/console/userinfo/endpoint.go)

**Comment by halkyon** [comment]
It looks like https://github.com/storj/storj/blob/e6217d6e6658ee525504c5edb22c4bc614582a82/satellite/metainfo/endpoint.go#L194 already has the public project ID in the response. Maybe we can use that instead?

**Comment by halkyon** [comment]
https://review.dev.storj.io/c/storj/uplink/+/13379

**Comment by halkyon** [comment]
Looks like this should work. I whipped up a quick example that feeds it into an eventkit feed, with some code like this:

```
projectIDBytes, err := privateProject.GetPublicID(r.Context(), uplink.Config{}, access)
if err == nil {
  projectUUID, _ = uuid.FromBytes(projectIDBytes)
}

...

ek.Event("gmt",
  eventkit.String("public-project-id", projectUUID.String()),
...
```

Confirmed I get the correct public project ID for my project on AP1 satellite.

**Comment by amwolff** [comment]
oh, this is a great find! yeah, next step is #439. We don't need to backfill old records. Just include the ID in the new ones.
