### ISSUE TITLE
Adjust GetObjectRetention gateway endpoint (object retention)

### ISSUE THREAD

**Issue by amwolff** [storj/edge#451]
This is an issue corresponding to #428, representing the work to complete adjustments to the GetObjectRetention gateway endpoint in the agreed scope of the Object Lock implementation.

**Comment by VitaliiShpital** [comment]
actually the above change is almost a duplicate of @wilfred-asomanii's change here
https://review.dev.storj.io/c/storj/gateway/+/13967/4

I abandoned my change since there are already some reviews
