### ISSUE TITLE
Linksharing UI: Update sidebar for inline and geofenced files

### ISSUE THREAD

**Issue by mobyvb** [storj/edge#464]
Current sidebar for inline file: 

![Image](https://github.com/user-attachments/assets/16ed8600-705d-42b6-909a-eb3ef7f54e5a)

This information ("You're getting this file from all over the world") is not accurate for very small files. Similarly, the text may not be accurate if the file is in a geofenced bucket.

### AC:
* update text and image in sidebar to be accurate information for inline files
* update text in sidebar to be accurate information for geofenced files
* prefer using Go template logic rather than JS for these branches - that way the way the UI looks is managed from the backend and does not rely on user having JS enabled to work

**Comment by NiaStorj** [comment]
@boshevski please provide copy for this ticket

**Comment by boshevski** [comment]
### Globally Distributed Files:

**Heading:**
You are downloading this file from all over the world

**Text:**
Storj splits your file into secure pieces, distributing them across a global network of storage suppliers. When you download, the pieces are securely put back together for you. The map below shows where your file's pieces are currently being stored.

**Node count box:**
Stored by 65 Storj storage suppliers worldwide.


### Region Files:

**Heading:**
You are downloading this file from the Storj network

**Text:**
Storj splits your file into secure pieces, distributing them across a global network of storage suppliers. When you download, the pieces are securely put back together for you. The map below shows where your file's pieces are currently being stored.

**Node count box:**
Stored by 65 Storj storage suppliers.


### Inline Files
**Heading:**
This file is ready for download

**Text:**
This file is securely stored and ready for you to download. Click the button to start your download.

- **Remove node count box**
- **Remove map**
