### ISSUE TITLE
Draft design for PutObjectLockConfiguration

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#471]
### Goal

- Goal is to come up with an approach for implementing [PutObjectLockConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLockConfiguration.html)
- Ideally, we come up with something that doesn't require schema change, but if not at least know the scope so we can plan and set expectations

### Acceptance Criteria

- One of the following:
   - Issue(s) created with the tasks for implementing PutObjectLockConfiguration
   - Design doc detailing possible implementation

### Links

 - https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLockConfiguration.html
 - https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectLockConfiguration.html

#### New S3 Actions Supported

| S3 Action | Description | Notes |
|---|---|---|
| [PutObjectLockConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLockConfiguration.html) | Enables Object Lock configuration on a bucket. | **ObjectLockEnabled**: Indicates if Object Lock is enabled on the bucket. <br><br>**Rule**: Specifies the Object Lock rule (mode and period) for the bucket. The period can be either `Days` or `Years`. |

#### Existing operations to update

| S3 Action | Description | Updates |
|---|---|---|
| [GetObjectLockConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectLockConfiguration.html) | Retrieves the Object Lock configuration of a bucket. | Returns any Rule applied via PutObjectLockConfiguration. |

**Comment by ferristocrat** [comment]
Added the table of S3 actions impacted, so basically just `GetObjectLockConfiguration` in addition to the new `PutObjectLockConfiguration`

**Comment by jewharton** [comment]
Here's the design doc for a possible implementation: https://docs.google.com/document/d/1Ksz_78NagaOFCQBP7PH_7sOgnruR59SvtJc4cNEuq2E/edit?usp=sharing
