### ISSUE TITLE
Implement Object Lock Test Plan - Compliance Mode Only

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#472]
### Goal

- Implement test plan

### Acceptance Criteria

- Manual tests run as found in the test plan
- Issues created where tests fail 

### Links

- Test plan: https://docs.google.com/document/d/1pGOhPTJGec0OogL0bM-qYVgnV8C8S7O9G08yKPXWWU8/edit
- Test cases with commands: https://docs.google.com/spreadsheets/d/1Yfz1sSTRD2nTRAkgGJ27aAv7wTMJCd-74fJlujdNPBw/edit?usp=sharing

**Comment by amwolff** [comment]
> Manual tests run as found in the test plan

We should also automate the test plan (as an integration test, for example) so we don't catch any regressions with future releases. This shouldn't be too big of a hurdle after @halkyon reworked integration tests suite recently.

**Comment by halkyon** [comment]
Example of how object versioning was tested: https://github.com/storj/edge/blob/main/testsuite/server/integration_test.go#L341. This used to be a whole lot more code, but it's been abstracted away so you get given the running gateway and S3 credentials and can focus on writing the actual tests.

**Comment by NiaStorj** [comment]
9/10/24:

Compliance only tests have been implemented. 
Still need to test legal hold & governance
