### ISSUE TITLE
Adjust DeleteBucket gateway endpoint

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#486]
This is an issue corresponding to #474, representing the work to complete adjustments to the DeleteBucket gateway endpoint..

**Comment by wilfred-asomanii** [comment]
there's already a test [in gateway](https://github.com/storj/gateway-st/blob/5cd4b2f1254101891d7bd96414a03d97825e051b/testsuite/miniogw/gateway_test.go#L263-L265) to prevent force deleting buckets with object lock enabled. This applies regardless of the contents of the bucket
