### ISSUE TITLE
Implement Schema Changes for PutObjectLockConfiguration

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#502]
### Summary

This issue is a placeholder for any work needed for making the schema change and any associated migration to support PutObjectLockConfiguration.

The satellite database's bucket_metainfos table must have the following columns (See [design doc](https://docs.google.com/document/d/1Ksz_78NagaOFCQBP7PH_7sOgnruR59SvtJc4cNEuq2E/edit#heading=h.cgicj0oiyzwg) for more details):

- `default_retention_mode` - A numeric column indicating the default retention mode of objects uploaded into this bucket. It should be NULL, storj.ComplianceMode (1), or storj.GovernanceMode (3).
- `default_retention_days` - A numeric column indicating the default amount of time, in days, for which objects uploaded into this bucket should be retained. One or neither of this column and default_retention_years should be set.
- `default_retention_years` - A numeric column indicating the default amount of time, in years, for which objects uploaded into this bucket should be retained. One or neither of this column and default_retention_days should be set.

**Comment by NiaStorj** [comment]
9/19/24:

blocked due to waiting for all of the spanner tests to pass.  at the moment the satellite team doesn't have a date on when that will be
