### ISSUE TITLE
Create a design doc for more robust DeleteObjects

### ISSUE THREAD

**Issue by amwolff** [storj/edge#508]
There actually is a design doc written by @wthorp already:

https://review.dev.storj.io/c/storj/storj/+/11352?usp=dashboard

It might be as "easy" as reviewing and merging it to make sure it captures everything that the [roadmap item](https://github.com/storj/roadmap/issues/91) talks about.

**Comment by jewharton** [comment]
https://github.com/storj/design-docs/pull/17
