### ISSUE TITLE
Update PutObject satellite endpoint to use default retention settings

### ISSUE THREAD

**Issue by jewharton** [storj/edge#513]
## Goal

This issue aims to make meaningful progress on Object Lock implementation within core and edge services. Specifically, this will help us support immutable backups in backup software products such as Veeam.

## What needs to be done? • Acceptance Criteria

Modify the satellite implementation of the `PutObject` operation such that if no retention configuration is provided for an object,
a default retention configuration is set based on the bucket's default retention policy (set via the `PutObjectLockConfiguration` operation).

## Depends on…

- storj/edge#502

## Links

- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLockConfiguration.html
- Documentation on S3 Object Lock: [Using S3 Object Lock](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html)

**Comment by halkyon** [comment]
Related issue: https://github.com/storj/edge/issues/512
